In [1]:
from keras.models import Sequential
from keras.layers.core import Activation,Dense,Dropout,Flatten
from keras.layers.convolutional import MaxPooling2D,Convolution2D
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import keras

Using TensorFlow backend.


In [2]:
data = pd.read_csv('mnist_data/train.csv')

In [3]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
data.iloc[3,1:].values #third row and all columns of first to until end with there data

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 220, 179,   6,   0,   0,   0,   0,   0,   0,   0,
         0,   9,  77,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,  28, 247,  17,   0,   0,   0,   

In [5]:
#reshape 28*28*1

In [6]:
df_x = data.iloc[:,1:].values.reshape(len(data),28,28,1) 

In [7]:
y = data.iloc[:,0].values

In [8]:
df_x.shape

(42000, 28, 28, 1)

In [9]:
y

array([1, 0, 1, ..., 7, 6, 9], dtype=int64)

In [10]:
df_y = keras.utils.to_categorical(y,num_classes=10) #converting labels to ctegorical features

In [11]:
df_y

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [12]:
df_x = np.array(df_x)
df_y = np.array(df_y)

In [13]:
y

array([1, 0, 1, ..., 7, 6, 9], dtype=int64)

In [14]:
df_x.shape

(42000, 28, 28, 1)

In [15]:
x_train,x_test,y_train,y_test = train_test_split(df_x,df_y,test_size = 0.2,random_state = 4)

In [16]:
model = Sequential()
model.add(Convolution2D(32,3,data_format="channels_last",activation="relu",input_shape = (28,28,1)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(100))
model.add(Dropout(0.5))
model.add(Dense(10))
model.add(Activation("softmax"))

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [17]:
model.compile(loss="categorical_crossentropy",optimizer="adadelta",metrics=["accuracy"])

In [18]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 5408)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 100)               540900    
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1010      
_________________________________________________________________
activation_1 (Activation)    (None, 10)                0         
Total para

In [19]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10)

Instructions for updating:
Use tf.cast instead.
Train on 33600 samples, validate on 8400 samples
Epoch 1/10
33600/33600 [==============================] - 8s 242us/step - loss: 9.9023 - acc: 0.3813 - val_loss: 6.4342 - val_acc: 0.5950
Epoch 2/10
33600/33600 [==============================] - 5s 151us/step - loss: 3.5405 - acc: 0.7695 - val_loss: 1.0917 - val_acc: 0.9226
Epoch 3/10
33600/33600 [==============================] - 5s 146us/step - loss: 1.1190 - acc: 0.9188 - val_loss: 0.6273 - val_acc: 0.9529
Epoch 4/10
33600/33600 [==============================] - 5s 147us/step - loss: 0.7180 - acc: 0.9425 - val_loss: 0.4743 - val_acc: 0.9610
Epoch 5/10
33600/33600 [==============================] - 5s 147us/step - loss: 0.5210 - acc: 0.9541 - val_loss: 0.4061 - val_acc: 0.9614
Epoch 6/10
33600/33600 [==============================] - 5s 149us/step - loss: 0.3205 - acc: 0.9565 - val_loss: 0.1692 - val_acc: 0.9610
Epoch 7/10
33600/33600 [==============================] - 5s 149us/step - l

In [22]:
model.evaluate(x_test,y_test) #for loss and accuracy value

8400/8400 [==============================] - 1s 103us/step


[0.10583576104429085, 0.9738095238095238]

In [23]:
model.predict(x_test) #prediction

array([[9.99998927e-01, 2.87562925e-11, 2.03662751e-07, ...,
        2.60176256e-11, 7.88746149e-07, 2.13534537e-10],
       [4.02977547e-11, 1.06173736e-09, 1.57771496e-12, ...,
        2.42434095e-09, 2.89149833e-11, 4.91113326e-07],
       [9.99997139e-01, 2.55902868e-11, 2.09072599e-08, ...,
        1.47176576e-10, 5.36071013e-07, 1.18911736e-07],
       ...,
       [9.96053696e-01, 1.42532087e-07, 6.73053009e-08, ...,
        4.04761348e-13, 1.99461980e-09, 1.90848420e-10],
       [5.77780960e-14, 1.89986351e-12, 6.30569555e-11, ...,
        4.17678891e-10, 3.51167206e-10, 2.20373941e-10],
       [1.50088101e-06, 9.99008596e-01, 5.24644638e-05, ...,
        9.21850551e-06, 8.87948670e-04, 2.31801073e-06]], dtype=float32)